#ifndef PARSER_ERRORS_H
#define PARSER_ERRORS_H 
#define PARSER_ERRORS_MARK 100
#define PARSER_SUCCESS_MARK 200

#define PARSER_ERROR_FORMAT_ERROR 1
#define PARSER_ERROR_FORMAT_ERROR_MSG "messge format error !"
#endif